/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MicroReaderPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/sm2.ts
function getTodayString() {
  const d = /* @__PURE__ */ new Date();
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}
function getTomorrowString() {
  const d = /* @__PURE__ */ new Date();
  d.setDate(d.getDate() + 1);
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}
function addDays(dateStr, days) {
  const d = /* @__PURE__ */ new Date(dateStr + "T00:00:00");
  d.setDate(d.getDate() + days);
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}
var SM2Engine = class _SM2Engine {
  static getPendingReviews(data) {
    const today = getTodayString();
    const maxDaily = data.settings.maxReviewsPerDay;
    const completedToday = data.dailyStats[today] || 0;
    const quota = Math.max(0, maxDaily - completedToday);
    if (quota <= 0)
      return [];
    const eligible = data.reviews.filter(
      (r) => r.dueDate <= today && !r.isLeech
    );
    eligible.sort((a, b) => a.dueDate.localeCompare(b.dueDate));
    return eligible.slice(0, quota);
  }
  static hasPendingReviews(data) {
    return _SM2Engine.getPendingReviews(data).length > 0;
  }
  static processIncrementalReview(item, direction, leechThreshold) {
    const step = direction === item.lastDirection ? item.lastStep * 2 : 1;
    let newStageIndex = item.stageIndex;
    if (direction === "up") {
      newStageIndex = Math.min(100, item.stageIndex + step);
    } else {
      newStageIndex = Math.max(-100, item.stageIndex - step);
    }
    if (newStageIndex >= 100) {
      const newResetCount = item.resetCount + 1;
      return {
        ...item,
        stageIndex: 0,
        lastDirection: null,
        lastStep: 0,
        resetCount: newResetCount,
        isLeech: newResetCount >= leechThreshold,
        repetitionNumber: 0,
        intervalDays: 1,
        dueDate: getTomorrowString(),
        lastReviewedAt: (/* @__PURE__ */ new Date()).toISOString()
      };
    }
    const q = 2.5 - newStageIndex / 100 * 2.5;
    let rep = item.repetitionNumber;
    let interval = item.intervalDays;
    let ef = item.easinessFactor;
    ef = ef + (0.1 - (5 - q) * (0.08 + (5 - q) * 0.02));
    if (ef < 1.3)
      ef = 1.3;
    if (q < 3) {
      rep = 0;
      interval = 1;
    } else {
      if (rep === 0) {
        interval = 1;
      } else if (rep === 1) {
        interval = 6;
      } else {
        interval = Math.round(interval * ef);
      }
      rep += 1;
    }
    const today = getTodayString();
    const nextDue = addDays(today, interval);
    return {
      ...item,
      stageIndex: newStageIndex,
      lastDirection: direction,
      lastStep: step,
      repetitionNumber: rep,
      intervalDays: interval,
      easinessFactor: ef,
      dueDate: nextDue,
      lastReviewedAt: (/* @__PURE__ */ new Date()).toISOString()
    };
  }
};

// src/zettelManager.ts
var import_obsidian = require("obsidian");

// src/parser.ts
var TextSimilarity = class {
  /**
   * Remove pontuação, números isolados e converte para minúsculas
   */
  static tokenize(text) {
    return text.toLowerCase().replace(/[^\p{L}\p{N}\s]/gu, " ").split(/\s+/).filter((w) => w.length > 1);
  }
  /**
   * Gera conjunto de bi-gramas (pares de palavras consecutivas)
   */
  static getBigrams(tokens) {
    const bigrams = /* @__PURE__ */ new Set();
    for (let i = 0; i < tokens.length - 1; i++) {
      bigrams.add(`${tokens[i]}_${tokens[i + 1]}`);
    }
    return bigrams;
  }
  /**
   * Calcula similaridade de Jaccard baseada em bi-gramas (0 a 100%)
   */
  static calculateSimilarityPercent(original, rewritten) {
    const origTokens = this.tokenize(original);
    const rewTokens = this.tokenize(rewritten);
    if (origTokens.length === 0 || rewTokens.length === 0)
      return 0;
    if (origTokens.length < 3 || rewTokens.length < 3) {
      const origSet = new Set(origTokens);
      const rewSet = new Set(rewTokens);
      let intersection = 0;
      for (const t of rewSet) {
        if (origSet.has(t))
          intersection++;
      }
      const union2 = (/* @__PURE__ */ new Set([...origSet, ...rewSet])).size;
      return union2 === 0 ? 0 : Math.round(intersection / union2 * 100);
    }
    const origBigrams = this.getBigrams(origTokens);
    const rewBigrams = this.getBigrams(rewTokens);
    if (origBigrams.size === 0 || rewBigrams.size === 0)
      return 0;
    let shared = 0;
    for (const bg of rewBigrams) {
      if (origBigrams.has(bg))
        shared++;
    }
    const union = (/* @__PURE__ */ new Set([...origBigrams, ...rewBigrams])).size;
    const similarity = union === 0 ? 0 : shared / union * 100;
    return Math.round(similarity);
  }
  /**
   * Avalia a extensão do texto em relação aos parâmetros ideais de um Zettel
   */
  static evaluateZettelLength(text) {
    const trimmed = text.trim();
    const words = trimmed ? trimmed.split(/\s+/).filter((w) => w.length > 0).length : 0;
    const chars = trimmed.length;
    if (words < 40) {
      return {
        words,
        chars,
        statusText: `\u26A0\uFE0F Curto (${words} palavras) \u2014 Defini\xE7\xE3o r\xE1pida`,
        statusType: "too_short"
      };
    } else if (words <= 250) {
      return {
        words,
        chars,
        statusText: `\u2713 Extens\xE3o ideal Zettel (${words} palavras / ~${chars} chars)`,
        statusType: "ideal"
      };
    } else {
      return {
        words,
        chars,
        statusText: `\u26A0\uFE0F Longo (${words} palavras) \u2014 Considere desmembrar com '---'`,
        statusType: "long"
      };
    }
  }
};
var MarkdownParser = class {
  /**
   * Extrai notas de rodapé estilo Obsidian: [^1]: texto
   */
  static extractFootnotes(content) {
    const footnotes = {};
    const lines = content.split("\n");
    const remainingLines = [];
    const fnStartRegex = /^\[\^([^\]]+)\]:\s*(.*)$/;
    let currentFnId = null;
    for (const line of lines) {
      const match = fnStartRegex.exec(line);
      if (match) {
        currentFnId = match[1];
        footnotes[currentFnId] = match[2].trim();
      } else if (currentFnId && (line.startsWith("    ") || line.startsWith("	"))) {
        footnotes[currentFnId] += " " + line.trim();
      } else {
        currentFnId = null;
        remainingLines.push(line);
      }
    }
    return {
      cleanContent: remainingLines.join("\n"),
      footnotes
    };
  }
  /**
   * Extrai links internos [[x]] de um texto
   */
  static extractInternalLinks(text) {
    const linkRegex = /\[\[([^\]]+)\]\]/g;
    const links = [];
    let match;
    while ((match = linkRegex.exec(text)) !== null) {
      let target = match[1];
      if (target.includes("|")) {
        target = target.split("|")[0];
      }
      if (target.includes("#")) {
        target = target.split("#")[0];
      }
      target = target.trim();
      if (target && !links.includes(target)) {
        links.push(target);
      }
    }
    return links;
  }
  /**
   * Divide o conteúdo em parágrafos semânticos
   */
  static parse(content) {
    const normalized = content.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
    const frontmatterRegex = /^---\n([\s\S]*?)\n---\n/;
    const contentWithoutFrontmatter = normalized.replace(frontmatterRegex, "");
    const { cleanContent, footnotes } = this.extractFootnotes(contentWithoutFrontmatter);
    const rawBlocks = cleanContent.split(/\n\s*\n/);
    const paragraphs = [];
    let globalIdx = 0;
    let currentSection = 1;
    for (const block of rawBlocks) {
      const trimmed = block.trim();
      if (!trimmed)
        continue;
      if (trimmed.startsWith("#")) {
        currentSection++;
        continue;
      }
      const cleanText = trimmed.split("\n").map((l) => l.trim()).filter((l) => l.length > 0).join(" ");
      if (cleanText.length >= 10) {
        paragraphs.push({
          index: globalIdx,
          text: cleanText,
          section: currentSection,
          internalLinks: this.extractInternalLinks(cleanText)
        });
        globalIdx++;
      }
    }
    return { paragraphs, footnotes };
  }
};
var FOOTER_MARKER = "<!-- microreader:footer -->";
var ZettelFooterParser = class {
  static split(fileContent) {
    const markerIdx = fileContent.indexOf(FOOTER_MARKER);
    if (markerIdx !== -1) {
      return {
        body: fileContent.substring(0, markerIdx).trim(),
        footer: fileContent.substring(markerIdx).trim()
      };
    }
    return this.migrateLegacyFormat(fileContent);
  }
  static migrateLegacyFormat(fileContent) {
    const origemRegex = /\*\*Origem:\*\*\s*\[\[([^\]]+)\]\]/g;
    const origens = [];
    let match;
    while ((match = origemRegex.exec(fileContent)) !== null) {
      origens.push(match[1]);
    }
    let body = fileContent.replace(/^#zettel\s*$/gm, "").replace(/\*\*Origem:\*\*\s*\[\[([^\]]+)\]\]/g, "").replace(/\n{3,}/g, "\n\n").trim();
    const origensUnicas = [...new Set(origens)];
    const footerLines = [
      FOOTER_MARKER,
      "#zettel",
      ...origensUnicas.map((o) => `**Origem:** [[${o}]]`)
    ];
    return { body, footer: footerLines.join("\n") };
  }
  static join(body, footer) {
    return `${body.trim()}

${footer.trim()}
`;
  }
};

// src/zettelManager.ts
var ZettelManager = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Verifica se a nota possui a tag exigida (ex: #zettel)
   */
  hasZettelTag(file, requiredTag = "zettel") {
    const cache = this.app.metadataCache.getFileCache(file);
    if (!cache)
      return false;
    const cleanTag = requiredTag.replace(/^#/, "").toLowerCase();
    if (cache.frontmatter && cache.frontmatter.tags) {
      const tags = cache.frontmatter.tags;
      if (Array.isArray(tags)) {
        if (tags.some((t) => String(t).replace(/^#/, "").toLowerCase() === cleanTag))
          return true;
      } else if (typeof tags === "string") {
        if (tags.split(/[\s,]+/).some((t) => t.replace(/^#/, "").toLowerCase() === cleanTag))
          return true;
      }
    }
    if (cache.tags) {
      if (cache.tags.some((t) => t.tag.replace(/^#/, "").toLowerCase() === cleanTag))
        return true;
    }
    return false;
  }
  /**
   * Lista todas as notas do Vault que possuem a tag #zettel
   */
  getAllZettelFiles(requiredTag = "zettel") {
    const files = this.app.vault.getMarkdownFiles();
    return files.filter((f) => this.hasZettelTag(f, requiredTag));
  }
  /**
   * Cria uma nova nota Zettelkasten:
   * - Contém a síntese
   * - Adiciona a tag #zettel
   * - Referencia no final o arquivo de origem [[Origem]]
   */
  async createZettelNote(title, content, sourceFile, requiredTag = "zettel") {
    const cleanTitle = title.replace(/[\\/:*?"<>|]/g, "").replace(/^\[\[|\]\]$/g, "").trim();
    const sourceBaseName = sourceFile.basename;
    const tagFormatted = requiredTag.startsWith("#") ? requiredTag : `#${requiredTag}`;
    const noteBody = `${content}

<!-- microreader:footer -->
${tagFormatted}

**Origem:** [[${sourceBaseName}]]
`;
    const parentPath = sourceFile.parent?.path || "";
    const filePath = parentPath ? `${parentPath}/${cleanTitle}.md` : `${cleanTitle}.md`;
    const existing = this.app.vault.getAbstractFileByPath(filePath);
    if (existing instanceof import_obsidian.TFile) {
      await this.mergeWithExistingZettel(existing, content, sourceFile);
      return existing;
    }
    return await this.app.vault.create(filePath, noteBody);
  }
  /**
   * Mescla a nova síntese com uma nota Zettel existente
   */
  async mergeWithExistingZettel(targetFile, content, sourceFile) {
    const sourceBaseName = sourceFile.basename;
    const fileContent = await this.app.vault.read(targetFile);
    const { body, footer } = ZettelFooterParser.split(fileContent);
    const newBody = `${body}

---
### Adi\xE7\xE3o Incremental
${content}`;
    const newFooter = footer.includes(sourceBaseName) ? footer : `${footer}
**Origem:** [[${sourceBaseName}]]`;
    await this.app.vault.modify(targetFile, ZettelFooterParser.join(newBody, newFooter));
  }
  /**
   * Substitui o parágrafo no arquivo de origem por um ou mais links [[Nota Criada]]
   */
  async replaceParagraphWithLinks(sourceFile, originalParagraphText, zettelTitles) {
    const linkStr = zettelTitles.map((t) => `[[${t.replace(/^\[\[|\]\]$/g, "").trim()}]]`).join(" ");
    const fileContent = await this.app.vault.read(sourceFile);
    if (fileContent.includes(originalParagraphText)) {
      const updated = fileContent.replace(originalParagraphText, linkStr);
      await this.app.vault.modify(sourceFile, updated);
    }
  }
  async replaceParagraphWithLink(sourceFile, originalParagraphText, zettelTitle) {
    return this.replaceParagraphWithLinks(sourceFile, originalParagraphText, [zettelTitle]);
  }
};

// src/views/ReadingModal.ts
var import_obsidian3 = require("obsidian");

// src/views/ZettelSuggestModal.ts
var import_obsidian2 = require("obsidian");
var ZettelSuggestModal = class extends import_obsidian2.SuggestModal {
  constructor(app, files, onChoose) {
    super(app);
    this.files = files;
    this.onChoose = onChoose;
    this.setPlaceholder("Pesquise uma nota com #zettel para mesclar...");
  }
  getSuggestions(query) {
    const q = query.toLowerCase();
    return this.files.filter((f) => f.basename.toLowerCase().includes(q));
  }
  renderSuggestion(file, el) {
    el.createEl("div", { text: file.basename, cls: "microreader-suggest-title" });
    el.createEl("small", { text: file.path, cls: "microreader-suggest-path" });
  }
  onChooseSuggestion(file, evt) {
    this.onChoose(file);
  }
};

// src/views/ReadingModal.ts
var ReadingModal = class extends import_obsidian3.Modal {
  constructor(app, initialFile, data, onSaveData) {
    super(app);
    this.data = data;
    this.onSaveData = onSaveData;
    this.fileStack = [];
    this.paragraphs = [];
    this.footnotes = {};
    this.currentIdx = 0;
    this.currentFile = initialFile;
    this.fileStack = [initialFile];
    this.zettelManager = new ZettelManager(app);
  }
  async onOpen() {
    this.modalEl.addClass("microreader-zen-modal");
    await this.loadFile(this.currentFile);
  }
  async loadFile(file) {
    this.currentFile = file;
    const content = await this.app.vault.read(file);
    const parsed = MarkdownParser.parse(content);
    this.paragraphs = parsed.paragraphs;
    this.footnotes = parsed.footnotes;
    let docState = this.data.documents[file.path];
    if (!docState) {
      docState = {
        filePath: file.path,
        title: file.basename,
        currentParagraphIndex: 0,
        completedParagraphs: [],
        ignoredParagraphs: [],
        totalParagraphs: this.paragraphs.length,
        lastReadAt: (/* @__PURE__ */ new Date()).toISOString()
      };
      this.data.documents[file.path] = docState;
    } else {
      docState.totalParagraphs = this.paragraphs.length;
    }
    this.currentIdx = docState.currentParagraphIndex;
    while (this.currentIdx < this.paragraphs.length && (docState.completedParagraphs.includes(this.currentIdx) || docState.ignoredParagraphs.includes(this.currentIdx))) {
      this.currentIdx++;
    }
    this.renderParagraphView();
  }
  renderParagraphView() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("microreader-reading-container");
    const docState = this.data.documents[this.currentFile.path];
    if (this.currentIdx >= this.paragraphs.length) {
      if (this.fileStack.length > 1) {
        this.fileStack.pop();
        const parentFile = this.fileStack[this.fileStack.length - 1];
        new import_obsidian3.Notice(`Retornando \xE0 nota principal: ${parentFile.basename}`);
        this.loadFile(parentFile);
        return;
      } else {
        contentEl.createEl("h2", { text: "\u{1F3C6} Leitura Conclu\xEDda!" });
        contentEl.createEl("p", {
          text: `Voc\xEA analisou e reescreveu todos os par\xE1grafos de "${this.currentFile.basename}".`
        });
        const closeBtn = contentEl.createEl("button", {
          text: "Fechar",
          cls: "mod-cta"
        });
        closeBtn.onclick = () => this.close();
        return;
      }
    }
    const currentParagraph = this.paragraphs[this.currentIdx];
    const navBar = contentEl.createDiv({ cls: "microreader-navbar" });
    const titleEl = navBar.createEl("h3", {
      text: `\u{1F4D6} ${this.currentFile.basename}`
    });
    if (this.fileStack.length > 1) {
      navBar.createEl("span", {
        text: ` (N\xEDvel ${this.fileStack.length} da Pilha Recursiva)`,
        cls: "microreader-stack-level"
      });
    }
    const progressText = navBar.createEl("span", {
      text: `Par\xE1grafo ${this.currentIdx + 1} de ${this.paragraphs.length} (Bloco ${currentParagraph.section})`,
      cls: "microreader-progress-label"
    });
    const progressContainer = contentEl.createDiv({
      cls: "microreader-progressbar-bg"
    });
    const progressBar = progressContainer.createDiv({
      cls: "microreader-progressbar-fill"
    });
    const pct = Math.round(this.currentIdx / this.paragraphs.length * 100);
    progressBar.style.width = `${pct}%`;
    const paragraphCard = contentEl.createDiv({
      cls: "microreader-focus-card"
    });
    const pTextEl = paragraphCard.createDiv({
      cls: "microreader-paragraph-text"
    });
    this.renderParagraphWithFootnotes(pTextEl, currentParagraph.text);
    if (currentParagraph.internalLinks.length > 0) {
      const linkBox = paragraphCard.createDiv({
        cls: "microreader-internal-links-box"
      });
      linkBox.createEl("span", { text: "\u{1F517} Aprofundar Leitura Recursiva: " });
      for (const linkName of currentParagraph.internalLinks) {
        const linkBtn = linkBox.createEl("button", {
          text: `[[${linkName}]]`,
          cls: "microreader-link-button"
        });
        linkBtn.onclick = async () => {
          const targetFile = this.app.metadataCache.getFirstLinkpathDest(
            linkName,
            this.currentFile.path
          );
          if (targetFile instanceof import_obsidian3.TFile) {
            if (this.zettelManager.hasZettelTag(
              targetFile,
              this.data.settings.requiredTag
            )) {
              this.fileStack.push(targetFile);
              await this.loadFile(targetFile);
            } else {
              new import_obsidian3.Notice(
                `A nota [[${linkName}]] n\xE3o possui a tag #${this.data.settings.requiredTag}`
              );
            }
          } else {
            new import_obsidian3.Notice(`Nota n\xE3o encontrada: [[${linkName}]]`);
          }
        };
      }
    }
    const formCard = contentEl.createDiv({ cls: "microreader-form-card" });
    const toolsRow = formCard.createDiv({ cls: "microreader-tools-row" });
    toolsRow.createEl("label", {
      text: "Sua S\xEDntese At\xF4mica (Use '---' para desmembrar em m\xFAltiplas notas):",
      cls: "microreader-field-label"
    });
    const btnSplitSelection = toolsRow.createEl("button", {
      text: "\u2702\uFE0F Desmembrar Sele\xE7\xE3o (Inserir '---')",
      cls: "microreader-btn-tool"
    });
    (0, import_obsidian3.setTooltip)(
      btnSplitSelection,
      "Insere um delimitador '---' em volta do texto selecionado para criar notas Zettel separadas"
    );
    const textarea = formCard.createEl("textarea", {
      placeholder: "Digite sua s\xEDntese... Para criar duas ou mais notas at\xF4micas independentes, separe os trechos com '---'.",
      cls: "microreader-textarea"
    });
    const titlesContainer = formCard.createDiv({
      cls: "microreader-titles-container"
    });
    const getSections = () => {
      const val = textarea.value;
      return val.split(/\n\s*---\s*\n|(?:\r?\n)?---\r?\n/).map((s) => s.trim()).filter((s) => s.length > 0);
    };
    let titleInputs = [];
    const updateTitleFields = () => {
      const sections = getSections();
      const count = Math.max(1, sections.length);
      if (titleInputs.length !== count) {
        const oldValues = titleInputs.map((input) => input.value);
        titlesContainer.empty();
        titleInputs = [];
        if (count === 1) {
          titlesContainer.createEl("label", {
            text: "Defina o T\xEDtulo da Nota Zettelkasten:",
            cls: "microreader-field-label"
          });
          const inp = titlesContainer.createEl("input", {
            type: "text",
            placeholder: "ex: [[Princ\xEDpio da Repeti\xE7\xE3o Espa\xE7ada]]",
            cls: "microreader-title-input"
          });
          inp.value = oldValues[0] || "";
          inp.oninput = validate;
          titleInputs.push(inp);
        } else {
          titlesContainer.createEl("label", {
            text: `\u2702\uFE0F Notas Desmembradas (${count} notas at\xF4micas ser\xE3o criadas):`,
            cls: "microreader-field-label microreader-highlight-text"
          });
          for (let i = 0; i < count; i++) {
            const row = titlesContainer.createDiv({
              cls: "microreader-multi-title-row"
            });
            row.createEl("span", {
              text: `Nota #${i + 1}:`,
              cls: "microreader-badge-num"
            });
            const inp = row.createEl("input", {
              type: "text",
              placeholder: `ex: [[T\xEDtulo da Ideia ${i + 1}]]`,
              cls: "microreader-title-input"
            });
            inp.value = oldValues[i] || "";
            inp.oninput = validate;
            titleInputs.push(inp);
          }
        }
      }
    };
    btnSplitSelection.onclick = () => {
      const start = textarea.selectionStart;
      const end = textarea.selectionEnd;
      const val = textarea.value;
      if (start !== end) {
        const before = val.substring(0, start).trimEnd();
        const selected = val.substring(start, end).trim();
        const after = val.substring(end).trimStart();
        let newContent = "";
        if (before)
          newContent += before + "\n\n---\n\n";
        newContent += selected;
        if (after)
          newContent += "\n\n---\n\n" + after;
        textarea.value = newContent;
      } else {
        const before = val.substring(0, start).trimEnd();
        const after = val.substring(start).trimStart();
        textarea.value = (before ? before + "\n\n---\n\n" : "---\n\n") + after;
      }
      updateTitleFields();
      validate();
      textarea.focus();
    };
    const actionRow = formCard.createDiv({ cls: "microreader-action-row" });
    const btnIgnore = actionRow.createEl("button", {
      text: "\u{1F5D1}\uFE0F Ignorar Par\xE1grafo",
      cls: "microreader-btn-danger"
    });
    (0, import_obsidian3.setTooltip)(
      btnIgnore,
      "Descarta este par\xE1grafo sem criar revis\xE3o nem nota Zettel"
    );
    btnIgnore.onclick = async () => {
      docState.ignoredParagraphs.push(this.currentIdx);
      docState.currentParagraphIndex = this.currentIdx + 1;
      await this.onSaveData();
      this.currentIdx++;
      this.renderParagraphView();
    };
    const btnMerge = actionRow.createEl("button", {
      text: "\u{1F517} Mesclar com Nota Existente",
      cls: "microreader-btn-merge"
    });
    (0, import_obsidian3.setTooltip)(
      btnMerge,
      "Anexa esta s\xEDntese a uma nota com #zettel j\xE1 existente no Vault"
    );
    btnMerge.onclick = () => {
      const zettelFiles = this.zettelManager.getAllZettelFiles(
        this.data.settings.requiredTag
      );
      new ZettelSuggestModal(this.app, zettelFiles, async (chosen) => {
        const text = textarea.value.trim();
        if (text.split(/\s+/).length < this.data.settings.minRewriteWords) {
          new import_obsidian3.Notice(
            `Escreva ao menos ${this.data.settings.minRewriteWords} palavras antes de mesclar.`
          );
          return;
        }
        await this.zettelManager.mergeWithExistingZettel(
          chosen,
          text,
          this.currentFile
        );
        await this.zettelManager.replaceParagraphWithLink(
          this.currentFile,
          currentParagraph.text,
          chosen.basename
        );
        await this.scheduleReviewAndAdvance(
          [chosen.basename],
          currentParagraph,
          [text]
        );
      }).open();
    };
    const statusLabel = actionRow.createEl("span", {
      cls: "microreader-status-label"
    });
    const btnSubmit = actionRow.createEl("button", {
      text: "Criar Nota(s) Zettel e Avan\xE7ar (Ctrl+Enter)",
      cls: "mod-cta"
    });
    btnSubmit.disabled = true;
    const validate = () => {
      let hasHighSimilarity = false;
      let maxFoundSimilarity = 0;
      const sections = getSections();
      const count = Math.max(1, sections.length);
      const totalWords = textarea.value.trim().split(/\s+/).filter((w) => w.length > 0).length;
      for (const section of sections) {
        const similarity = TextSimilarity.calculateSimilarityPercent(
          currentParagraph.text,
          textarea.value
        );
        if (similarity > maxFoundSimilarity) {
          maxFoundSimilarity = similarity;
        }
        if (similarity > this.data.settings.maxSimilarityPercent) {
          hasHighSimilarity = true;
        }
      }
      if (hasHighSimilarity) {
        btnSubmit.disabled = true;
        statusLabel.setText(
          `\u26A0\uFE0F Muito parecido com o original (${maxFoundSimilarity}% de similaridade, m\xE1x. ${this.data.settings.maxSimilarityPercent}%)`
        );
        statusLabel.addClass("is-error");
      } else {
        if (totalWords < this.data.settings.minRewriteWords) {
          statusLabel.setText(
            `M\xEDnimo de ${this.data.settings.minRewriteWords} palavras (${totalWords}/${this.data.settings.minRewriteWords})`
          );
          btnSubmit.disabled = true;
          return false;
        }
        for (let i = 0; i < count; i++) {
          const inp = titleInputs[i];
          if (!inp || inp.value.trim().length < 2) {
            statusLabel.setText(`\u26A0\uFE0F Defina o t\xEDtulo da Nota #${i + 1}`);
            btnSubmit.disabled = true;
            return false;
          }
        }
        const noteStr = count > 1 ? `${count} notas desmembradas` : "1 nota";
        statusLabel.setText(
          `\u2713 Pronto para criar ${noteStr} (${totalWords} palavras)`
        );
        btnSubmit.disabled = false;
        return true;
      }
    };
    textarea.oninput = () => {
      updateTitleFields();
      validate();
    };
    updateTitleFields();
    const doSubmit = async () => {
      if (!validate())
        return;
      const sections = getSections();
      const titles = titleInputs.map((inp) => inp.value.trim());
      for (let i = 0; i < sections.length; i++) {
        await this.zettelManager.createZettelNote(
          titles[i],
          sections[i],
          this.currentFile,
          this.data.settings.requiredTag
        );
      }
      await this.zettelManager.replaceParagraphWithLinks(
        this.currentFile,
        currentParagraph.text,
        titles
      );
      await this.scheduleReviewAndAdvance(titles, currentParagraph, sections);
    };
    btnSubmit.onclick = doSubmit;
    textarea.onkeydown = (e) => {
      if ((e.ctrlKey || e.metaKey) && e.key === "Enter") {
        e.preventDefault();
        doSubmit();
      }
    };
    setTimeout(() => textarea.focus(), 50);
  }
  async scheduleReviewAndAdvance(zettelTitles, block, rewrittenSections) {
    const docState = this.data.documents[this.currentFile.path];
    for (let i = 0; i < zettelTitles.length; i++) {
      const zTitle = zettelTitles[i].replace(/^\[\[|\]\]$/g, "").trim();
      const content = rewrittenSections[i] || rewrittenSections[0];
      this.data.reviews.push({
        id: `${this.currentFile.path}#${block.index}#${i}#${Date.now()}`,
        sourceFilePath: this.currentFile.path,
        paragraphIndex: block.index,
        originalText: block.text,
        rewrittenText: content,
        zettelTitle: zTitle,
        repetitionNumber: 0,
        intervalDays: 1,
        easinessFactor: 2.5,
        dueDate: getTomorrowString(),
        stageIndex: 0,
        lastDirection: null,
        lastStep: 0,
        resetCount: 0,
        isLeech: false,
        rewriteHistory: []
      });
    }
    docState.completedParagraphs.push(this.currentIdx);
    docState.currentParagraphIndex = this.currentIdx + 1;
    docState.lastReadAt = (/* @__PURE__ */ new Date()).toISOString();
    await this.onSaveData();
    this.currentIdx++;
    this.renderParagraphView();
  }
  /**
   * Renderiza o parágrafo convertendo [^1] em badges com tooltip nativo do Obsidian
   */
  renderParagraphWithFootnotes(container, text) {
    const fnRegex = /\[\^([^\]]+)\]/g;
    let lastIdx = 0;
    let match;
    while ((match = fnRegex.exec(text)) !== null) {
      const before = text.substring(lastIdx, match.index);
      if (before)
        container.appendText(before);
      const fnId = match[1];
      const fnBadge = container.createEl("span", {
        text: `[${fnId}]`,
        cls: "microreader-footnote-badge"
      });
      const noteText = this.footnotes[fnId] || "Nota de rodap\xE9 n\xE3o encontrada";
      (0, import_obsidian3.setTooltip)(fnBadge, `\u{1F50D} Nota de Rodap\xE9: ${noteText}`);
      lastIdx = match.index + match[0].length;
    }
    const rest = text.substring(lastIdx);
    if (rest)
      container.appendText(rest);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/views/ReviewModal.ts
var import_obsidian4 = require("obsidian");
var ReviewModal = class extends import_obsidian4.Modal {
  constructor(app, data, onSaveData, onCompletedAll) {
    super(app);
    this.data = data;
    this.onSaveData = onSaveData;
    this.onCompletedAll = onCompletedAll;
    this.currentIdx = 0;
    this.pendingReviews = [];
    this.currentZettelFile = null;
    this.currentSplit = null;
    this.pendingReviews = SM2Engine.getPendingReviews(this.data);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("microreader-modal");
    if (this.pendingReviews.length === 0) {
      contentEl.createEl("h2", { text: "\u{1F389} Nenhuma revis\xE3o pendente!" });
      contentEl.createEl("p", {
        text: "Sua fila di\xE1ria est\xE1 limpa. Voc\xEA pode prosseguir com as leituras novas."
      });
      const btn = contentEl.createEl("button", {
        text: "Iniciar Leitura",
        cls: "mod-cta"
      });
      btn.onclick = () => {
        this.close();
        this.onCompletedAll();
      };
      return;
    }
    this.renderCurrentReview();
  }
  async resolveAndLoadZettel(item) {
    const file = this.app.metadataCache.getFirstLinkpathDest(item.zettelTitle, "");
    if (!(file instanceof import_obsidian4.TFile)) {
      this.currentZettelFile = null;
      this.currentSplit = null;
      return false;
    }
    const content = await this.app.vault.read(file);
    this.currentZettelFile = file;
    this.currentSplit = ZettelFooterParser.split(content);
    return true;
  }
  renderCurrentReview() {
    const { contentEl } = this;
    contentEl.empty();
    const item = this.pendingReviews[this.currentIdx];
    const total = this.pendingReviews.length;
    this.resolveAndLoadZettel(item).then((found) => {
      if (!found) {
        this.renderNotFoundState(item);
      } else {
        this.renderReviewForm(item, total);
      }
    });
  }
  renderNotFoundState(item) {
    const { contentEl } = this;
    const card = contentEl.createDiv({ cls: "microreader-card" });
    card.createEl("h3", { text: `\u26A0\uFE0F Zettel n\xE3o encontrado` });
    card.createEl("p", {
      text: `O arquivo "${item.zettelTitle}" foi deletado ou renomeado?`
    });
    const btnRow = card.createDiv({ cls: "microreader-action-row" });
    const btnRemove = btnRow.createEl("button", { text: "Remover da Fila", cls: "microreader-btn-danger" });
    btnRemove.onclick = async () => {
      this.data.reviews = this.data.reviews.filter((r) => r.id !== item.id);
      await this.onSaveData();
      this.advanceToNext();
    };
    const btnSkip = btnRow.createEl("button", { text: "Pular", cls: "microreader-btn-merge" });
    btnSkip.onclick = () => this.advanceToNext();
  }
  renderReviewForm(item, total) {
    const { contentEl } = this;
    const alertBox = contentEl.createDiv({ cls: "microreader-gatekeeper-banner" });
    alertBox.createEl("span", {
      text: `\u26A0\uFE0F Gatekeeper Ativo: Revis\xE3o ${this.currentIdx + 1} de ${total}.`
    });
    const card = contentEl.createDiv({ cls: "microreader-card" });
    card.createEl("h3", { text: `Nota: [[${item.zettelTitle}]]`, cls: "microreader-title" });
    if (item.resetCount > 0) {
      card.createEl("div", {
        text: `\u{1FA78} J\xE1 resetou ${item.resetCount}x. Com ${this.data.settings.leechThreshold}x vira leech.`,
        cls: "microreader-leech-warning"
      });
    }
    card.createEl("label", { text: "Texto Original (fonte, somente leitura):" });
    const origBox = card.createDiv({ cls: "microreader-display-box" });
    origBox.setText(item.originalText);
    card.createEl("label", { text: "Sua Reescrita (edite livremente):" });
    const textarea = card.createEl("textarea", { cls: "microreader-textarea" });
    const originalBody = this.currentSplit.body;
    textarea.value = originalBody;
    const ratingContainer = card.createDiv({ cls: "microreader-ratings-row" });
    const btnUp = ratingContainer.createEl("button", { text: "\u{1F53A} +Prioridade (n\xE3o lembrei bem)", cls: "mr-btn-up" });
    const btnDown = ratingContainer.createEl("button", { text: "\u{1F53B} -Prioridade (lembrei bem)", cls: "mr-btn-down" });
    btnUp.onclick = () => this.handleRate(item, "up", textarea.value, originalBody);
    btnDown.onclick = () => this.handleRate(item, "down", textarea.value, originalBody);
    setTimeout(() => textarea.focus(), 50);
  }
  async handleRate(item, direction, newBody, oldBody) {
    const trimmedNew = newBody.trim();
    const trimmedOld = oldBody.trim();
    if (trimmedNew !== trimmedOld) {
      item.rewriteHistory.push({
        date: (/* @__PURE__ */ new Date()).toISOString(),
        text: trimmedOld
      });
      const fullContent = ZettelFooterParser.join(trimmedNew, this.currentSplit.footer);
      await this.app.vault.modify(this.currentZettelFile, fullContent);
    }
    const leechThreshold = this.data.settings.leechThreshold;
    const updated = SM2Engine.processIncrementalReview(item, direction, leechThreshold);
    const idx = this.data.reviews.findIndex((r) => r.id === item.id);
    if (idx !== -1) {
      this.data.reviews[idx] = { ...updated, rewriteHistory: item.rewriteHistory };
    }
    if (updated.isLeech && !item.isLeech) {
      new import_obsidian4.Notice(`\u{1FA78} "${item.zettelTitle}" virou leech (${updated.resetCount} resets).`);
    }
    const today = getTodayString();
    this.data.dailyStats[today] = (this.data.dailyStats[today] || 0) + 1;
    await this.onSaveData();
    this.advanceToNext();
  }
  advanceToNext() {
    this.currentIdx++;
    if (this.currentIdx < this.pendingReviews.length) {
      this.renderCurrentReview();
    } else {
      new import_obsidian4.Notice("\u2705 Revis\xF5es do dia conclu\xEDdas! Leitura destravada.");
      this.close();
      this.onCompletedAll();
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  maxReviewsPerDay: 20,
  minRewriteWords: 3,
  maxSimilarityPercent: 55,
  autoTagZettel: true,
  requiredTag: "zettel",
  fontSizePx: 20,
  leechThreshold: 3
};
var DEFAULT_DATA = {
  settings: DEFAULT_SETTINGS,
  reviews: [],
  documents: {},
  dailyStats: {}
};
var MicroReaderPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.data = DEFAULT_DATA;
  }
  async onload() {
    await this.loadPluginData();
    this.zettelManager = new ZettelManager(this.app);
    this.addRibbonIcon(
      "book-open",
      "microReader: Iniciar Leitura Incremental",
      () => {
        this.startIncrementalReading();
      }
    );
    this.addCommand({
      id: "start-reading",
      name: "Iniciar Leitura Incremental da Nota Atual",
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile && activeFile.extension === "md") {
          if (!checking) {
            this.startIncrementalReading(activeFile);
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "open-reviews",
      name: "Abrir Fila de Revis\xF5es Di\xE1rias (SM-2)",
      callback: () => {
        new ReviewModal(
          this.app,
          this.data,
          () => this.savePluginData(),
          () => {
            new import_obsidian5.Notice("Fila de revis\xF5es limpa!");
          }
        ).open();
      }
    });
    this.addSettingTab(new MicroReaderSettingTab(this.app, this));
  }
  async startIncrementalReading(file) {
    if (SM2Engine.hasPendingReviews(this.data)) {
      new import_obsidian5.Notice(
        "\u26A0\uFE0F Gatekeeper Ativo: Complete as revis\xF5es di\xE1rias antes de iniciar nova leitura."
      );
      new ReviewModal(
        this.app,
        this.data,
        () => this.savePluginData(),
        () => {
          this.openReadingForFile(file);
        }
      ).open();
      return;
    }
    this.openReadingForFile(file);
  }
  openReadingForFile(file) {
    const targetFile = file || this.app.workspace.getActiveFile();
    if (!targetFile || targetFile.extension !== "md") {
      new import_obsidian5.Notice("Abra ou selecione uma nota Markdown para ler.");
      return;
    }
    if (!this.zettelManager.hasZettelTag(
      targetFile,
      this.data.settings.requiredTag
    )) {
      new import_obsidian5.Notice(
        `A nota "${targetFile.basename}" precisa ter a tag #${this.data.settings.requiredTag} para ser lida no microReader.`
      );
      return;
    }
    new ReadingModal(
      this.app,
      targetFile,
      this.data,
      () => this.savePluginData()
    ).open();
  }
  async loadPluginData() {
    this.data = Object.assign({}, DEFAULT_DATA, await this.loadData());
    this.data.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      this.data.settings
    );
  }
  async savePluginData() {
    await this.saveData(this.data);
  }
};
var MicroReaderSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Configura\xE7\xF5es do microReader" });
    new import_obsidian5.Setting(containerEl).setName("Limite M\xE1ximo Di\xE1rio de Revis\xF5es").setDesc(
      "N\xFAmero m\xE1ximo de revis\xF5es apresentadas por dia para prevenir estafa e sobrecarga."
    ).addText(
      (text) => text.setValue(String(this.plugin.data.settings.maxReviewsPerDay)).onChange(async (val) => {
        const num = parseInt(val, 10);
        if (!isNaN(num) && num > 0) {
          this.plugin.data.settings.maxReviewsPerDay = num;
          await this.plugin.savePluginData();
        }
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Tag Obrigat\xF3ria para Leitura").setDesc(
      "Apenas notas que possuam esta tag ser\xE3o consideradas pelo leitor."
    ).addText(
      (text) => text.setValue(this.plugin.data.settings.requiredTag).onChange(async (val) => {
        this.plugin.data.settings.requiredTag = val.replace(/^#/, "").trim();
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("M\xEDnimo de Palavras na Reescrita").setDesc(
      "Exig\xEAncia m\xEDnima de elabora\xE7\xE3o ativa para poder criar a nota Zettel e avan\xE7ar."
    ).addText(
      (text) => text.setValue(String(this.plugin.data.settings.minRewriteWords)).onChange(async (val) => {
        const num = parseInt(val, 10);
        if (!isNaN(num) && num >= 1) {
          this.plugin.data.settings.minRewriteWords = num;
          await this.plugin.savePluginData();
        }
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Similaridade M\xE1xima Permitida (%)").setDesc(
      "Bloqueia o avan\xE7o caso a similaridade (N-gramas) com o par\xE1grafo original exceda esta porcentagem. Padr\xE3o: 55%."
    ).addText(
      (text) => text.setValue(String(this.plugin.data.settings.maxSimilarityPercent)).onChange(async (val) => {
        const num = parseInt(val, 10);
        if (!isNaN(num) && num >= 10 && num <= 95) {
          this.plugin.data.settings.maxSimilarityPercent = num;
          await this.plugin.savePluginData();
        }
      })
    );
  }
};
